### ISSUE TITLE
Hora do evento

### ISSUE THREAD

**Issue by octavioamu** [minasdev/minasdev-events#17]
Seria bom incluir a data junto com a hora que começa o evento.
(Podem fechar esta issue pra não misturar com os eventos)

**Comment by obetomuniz** [comment]
@octavioamu Interessante, penso que a melhor proposta para inserção seria:

### Titúlo da Issue:
```
[Nome do Evento] / [Data do Evento: YYYY-MM-DD]
```

### Conteúdo da Issue:
```
- Evento: [Nome do Evento](URL/Site do Evento)
- Local: [Local](URL do Google Maps)
- Data: YYYY-MM-DD
- Horário de Ínicio: HH:mm:ss [opcional]
- Horário de Término: HH:mm:ss [opcional]
- Descrição: Rápida descrição
```

O que acha?

**Comment by octavioamu** [comment]
no principio gostei, mas pensando mais um pouco ai ferra quando o evento tem mais de 1 dia, por isso talvez seja melhor:
Data inicio : YYYY-MM-DD h:mm a
Data final: YYYY-MM-DD h:mm a [opcional]

**Comment by obetomuniz** [comment]
@octavioamu o problema é que o padrão atual já usa o modelo `Data: "YYYY-MM-DD"`, e para atualizarmos pro formato que você propôs, seria preciso atualizar todos os eventos passados. Outro agravante, é que existem inúmeras possibilidades de agenda de evento. Pensando melhor, acredito que o modelo atual tem como proposta simplificar as coisas, não é a ideia oferecer todas as informações, e sim as cruciais para anunciar externamente o evento, sem contar que uma delas é o link do site do evento, e é lá que informações mais detalhadas são passadas.

**Comment by octavioamu** [comment]
Entendi.
